# Generated by Django 6.0.6 on 2026-07-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=111)),
                ('roll', models.IntegerField(max_length=11)),
                ('city', models.CharField(max_length=111)),
            ],
        ),
    ]
